const allProducts = [
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/71Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/914tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 350 },
      { inStock: 250 },
      { isBestSeller: false },
      { purchases: "500+ bought in past month" },
      { viewIn: "202 viewed last time" },
    ],
    name: "Apple iPhone 16 Pro",
    storage: "512 GB",
    color: "#1a1a1a",
    price: {
      current: 6299.0,
      original: 6699.0,
      discount: "8%",
    },
    rating: 4.0,
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    photos: [
      {
        mainPhoto:
          "https://m.media-amazon.com/images/I/61veAtnXzWL._AC_SL1500_.jpg",
      },
      {
        allPhotos: [
          "https://m.media-amazon.com/images/I/61Xb0ukxY-L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71sN31ykRtL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/71fj7myyDkL._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
          "https://m.media-amazon.com/images/I/814tk1uLy9L._AC_SL1500_.jpg",
        ],
      },
      {
        brandImage:
          "https://m.media-amazon.com/images/G/40/Apple/River/AuthorizedReseller_Black_EN_800x190_ME._CB572981095_.jpg",
      },
    ],
    marketing: [
      { sellBefore: 300 },
      { inStock: 200 },
      { isBestSeller: true },
      { purchases: "400+ bought in past month" },
      { viewIn: "102 viewed last time" },
    ],
    name: "Apple iPhone 16 Mini",
    storage: "128 GB",
    color: "#1a1a1a",
    price: {
      current: 4299.0,
      original: 4899.0,
      discount: "12%",
    },
    rating: 3.5,
    availableSizes: ["128GB", "256GB", "512GB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "64 GB",
    screenSize: "5.4 Inches",
    resolution: "1080 x 2340",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "5.4-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
];

export default allProducts;
