const detailsProducts = [
  {
    name: "Apple iPhone 16 Pro Max",
    storage: "256 GB",
    color: "#1a1a1a",
    price: {
      current: 5299.0,
      original: 5699.0,
      discount: "7%",
    },
    rating: 4.5,
    purchases: "400+ bought in past month",
    availableSizes: ["1TB", "256GB", "512TB"],
    availableColors: ["White Titanium", "Green", "Gray", "Silver", "Black"],
    brand: "Apple",
    operatingSystem: "iOS 15",
    memoryStorageCapacity: "128 GB",
    screenSize: "6.1 Inches",
    resolution: "1170 x 2532",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Midnight",
    features: [
      "6.1-inch Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    name: "Apple iPhone 14 Pro Max",
    storage: "512 GB",
    color: "#c0c0c0",
    price: {
      current: 4999.0,
      original: 5999.0,
      discount: "17%",
    },
    rating: 4.7,
    purchases: "300+ bought in past month",
    availableSizes: ["1TB", "512GB", "128GB"],
    availableColors: ["Green Titanium", "Gold", "Black", "Red"],
    brand: "Apple",
    operatingSystem: "iOS 14",
    memoryStorageCapacity: "512 GB",
    screenSize: "6.7 Inches",
    resolution: "1284 x 2778",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Silver",
    features: [
      "6.7-inch Super Retina XDR display",
      "ProMotion technology with adaptive refresh rates",
      "Triple-camera system with 12MP Ultra-Wide, Wide, and Telephoto cameras; Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A14 Bionic chip for powerful performance",
    ],
    reseller: "Authorized Reseller",
  },
  {
    name: "Apple iPhone 12 Pro Max",
    storage: "128 GB",
    color: "#474747",
    price: {
      current: 4399.0,
      original: 4999.0,
      discount: "12%",
    },
    rating: 4.4,
    purchases: "250+ bought in past month",
    availableSizes: ["256GB", "128GB", "512GB"],
    availableColors: ["Gold", "White", "Graphite", "Blue"],
    brand: "Apple",
    operatingSystem: "iOS 13",
    memoryStorageCapacity: "256 GB",
    screenSize: "6.5 Inches",
    resolution: "1242 x 2688",
    modelName: "iPhone",
    wirelessCarrier: "Unlocked for All Carriers",
    cellularTechnology: "5G",
    connectivityTechnology: ["Bluetooth", "Wi-Fi", "USB", "NFC"],
    colour: "Graphite",
    features: [
      "6.5-inch Super Retina XDR display",
      "Night mode photography and advanced video capabilities",
      "Triple-camera system with 12MP Ultra Wide, Wide, and Telephoto cameras; Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A13 Bionic chip for seamless performance",
    ],
    reseller: "Authorized Reseller",
  },
];

export default detailsProducts;
