const dummyProductsOne = [
  // Existing 20 products
  {
    name: "Smartphone X1",
    image: "/images/products/smartphone_x1.jpg",
    price: "499.99",
    rating: 4.5,
    isBestSeller: true,
  },
  {
    name: "Laptop Z Pro",
    image: "/images/products/laptop_z_pro.jpg",
    price: "799.99",
    rating: 4.2,
    isBestSeller: false,
  },
  {
    name: "Camera 360",
    image: "/images/products/camera_360.jpg",
    price: "599.99",
    rating: 4.7,
    isBestSeller: true,
  },
  {
    name: "Headphones XR",
    image: "/images/products/headphones_xr.jpg",
    price: "199.99",
    rating: 3.9,
    isBestSeller: false,
  },
  {
    name: "Smartwatch V1",
    image: "/images/products/smartwatch_v1.jpg",
    price: "249.99",
    rating: 4.3,
    isBestSeller: true,
  },
  {
    name: "Gaming Chair",
    image: "/images/products/gaming_chair.jpg",
    price: "299.99",
    rating: 4.1,
    isBestSeller: false,
  },
  {
    name: "Bluetooth Speaker",
    image: "/images/products/bluetooth_speaker.jpg",
    price: "99.99",
    rating: 4.4,
    isBestSeller: true,
  },
  {
    name: "Tablet S6",
    image: "/images/products/tablet_s6.jpg",
    price: "399.99",
    rating: 4.6,
    isBestSeller: true,
  },
  {
    name: "Action Camera 4K",
    image: "/images/products/action_camera_4k.jpg",
    price: "349.99",
    rating: 4.0,
    isBestSeller: false,
  },
  {
    name: "Electric Scooter",
    image: "/images/products/electric_scooter.jpg",
    price: "499.99",
    rating: 4.2,
    isBestSeller: true,
  },
  {
    name: "Laptop D5",
    image: "/images/products/laptop_d5.jpg",
    price: "899.99",
    rating: 4.3,
    isBestSeller: false,
  },
  {
    name: "Noise Cancelling Headphones",
    image: "/images/products/noise_cancelling_headphones.jpg",
    price: "149.99",
    rating: 4.6,
    isBestSeller: true,
  },
  {
    name: "Wireless Charger",
    image: "/images/products/wireless_charger.jpg",
    price: "39.99",
    rating: 4.5,
    isBestSeller: false,
  },
  {
    name: 'Smart TV 55"',
    image: "/images/products/smart_tv_55.jpg",
    price: "699.99",
    rating: 4.8,
    isBestSeller: true,
  },
  {
    name: "Portable Air Conditioner",
    image: "/images/products/portable_ac.jpg",
    price: "249.99",
    rating: 3.8,
    isBestSeller: false,
  },
  {
    name: "Electric Toothbrush",
    image: "/images/products/electric_toothbrush.jpg",
    price: "99.99",
    rating: 4.7,
    isBestSeller: true,
  },
  {
    name: "Fitness Tracker",
    image: "/images/products/fitness_tracker.jpg",
    price: "59.99",
    rating: 4.3,
    isBestSeller: false,
  },
  {
    name: "Smart Home Hub",
    image: "/images/products/smart_home_hub.jpg",
    price: "129.99",
    rating: 4.5,
    isBestSeller: true,
  },
  {
    name: "Robot Vacuum",
    image: "/images/products/robot_vacuum.jpg",
    price: "299.99",
    rating: 4.2,
    isBestSeller: false,
  },
  {
    name: "Bluetooth Mouse",
    image: "/images/products/bluetooth_mouse.jpg",
    price: "29.99",
    rating: 4.1,
    isBestSeller: true,
  },
  {
    name: "Gaming Keyboard",
    image: "/images/products/gaming_keyboard.jpg",
    price: "79.99",
    rating: 4.6,
    isBestSeller: true,
  },

  // Additional 20 products
  {
    name: "Digital Photo Frame",
    image: "/images/products/digital_photo_frame.jpg",
    price: "89.99",
    rating: 4.3,
    isBestSeller: false,
  },
  {
    name: "Virtual Reality Headset",
    image: "/images/products/vr_headset.jpg",
    price: "249.99",
    rating: 4.8,
    isBestSeller: true,
  },
  {
    name: "Home Security Camera",
    image: "/images/products/home_security_camera.jpg",
    price: "149.99",
    rating: 4.4,
    isBestSeller: true,
  },
  {
    name: "Smart Thermostat",
    image: "/images/products/smart_thermostat.jpg",
    price: "199.99",
    rating: 4.5,
    isBestSeller: false,
  },
  {
    name: "Electric Kettle",
    image: "/images/products/electric_kettle.jpg",
    price: "49.99",
    rating: 4.3,
    isBestSeller: false,
  },
  {
    name: "Instant Pot",
    image: "/images/products/instant_pot.jpg",
    price: "119.99",
    rating: 4.6,
    isBestSeller: true,
  },
  {
    name: "Cordless Vacuum",
    image: "/images/products/cordless_vacuum.jpg",
    price: "179.99",
    rating: 4.2,
    isBestSeller: false,
  },
  {
    name: "Smart Light Bulb",
    image: "/images/products/smart_light_bulb.jpg",
    price: "29.99",
    rating: 4.4,
    isBestSeller: true,
  },
  {
    name: "Wireless Camera",
    image: "/images/products/wireless_camera.jpg",
    price: "79.99",
    rating: 4.5,
    isBestSeller: true,
  },
  {
    name: "3D Printer",
    image: "/images/products/3d_printer.jpg",
    price: "499.99",
    rating: 4.7,
    isBestSeller: false,
  },
  {
    name: "Smart Door Lock",
    image: "/images/products/smart_door_lock.jpg",
    price: "149.99",
    rating: 4.6,
    isBestSeller: true,
  },
  {
    name: "Electric Grill",
    image: "/images/products/electric_grill.jpg",
    price: "99.99",
    rating: 4.1,
    isBestSeller: false,
  },
  {
    name: "Drone 1080p",
    image: "/images/products/drone_1080p.jpg",
    price: "299.99",
    rating: 4.8,
    isBestSeller: true,
  },
  {
    name: "Portable Generator",
    image: "/images/products/portable_generator.jpg",
    price: "399.99",
    rating: 4.2,
    isBestSeller: false,
  },
  {
    name: "E-Reader",
    image: "/images/products/e_reader.jpg",
    price: "129.99",
    rating: 4.3,
    isBestSeller: true,
  },
  {
    name: "Wireless Earbuds",
    image: "/images/products/wireless_earbuds.jpg",
    price: "89.99",
    rating: 4.4,
    isBestSeller: false,
  },
  {
    name: "Kitchen Scale",
    image: "/images/products/kitchen_scale.jpg",
    price: "19.99",
    rating: 4.1,
    isBestSeller: true,
  },
  {
    name: "Electric Pressure Cooker",
    image: "/images/products/electric_pressure_cooker.jpg",
    price: "149.99",
    rating: 4.5,
    isBestSeller: false,
  },
  {
    name: "Smart Speaker",
    image: "/images/products/smart_speaker.jpg",
    price: "79.99",
    rating: 4.7,
    isBestSeller: true,
  },
  {
    name: "Smart Fridge",
    image: "/images/products/smart_fridge.jpg",
    price: "1399.99",
    rating: 4.8,
    isBestSeller: false,
  },
];

export default dummyProductsOne;
